# Generated by Django 5.0 on 2024-02-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Quiz Category'},
        ),
    ]
