# Generated by Django 5.0.2 on 2024-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prev_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prev_questions',
            name='previous_question',
            field=models.FileField(blank=True, null=True, upload_to='previous_questions/'),
        ),
    ]
