# Generated by Django 4.2.4 on 2023-09-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_course_average_rating_course_rating_count_quizrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizrating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
