# Generated by Django 5.0 on 2024-02-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_description_question_has_time_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option10',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option7',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option8',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option9',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=200),
        ),
    ]
