# Generated by Django 5.0 on 2024-02-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_option1_question_a_rename_option2_question_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='a',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='c',
            new_name='option10',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='b',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='d',
            new_name='option3',
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4'), ('Option5', 'Option5'), ('Option6', 'Option6'), ('Option7', 'Option7'), ('Option8', 'Option8'), ('Option9', 'Option9'), ('Option10', 'Option10')], max_length=200),
        ),
    ]
